/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wssoftware.pracswing.views;

import com.ssoftware.pracswing.controllers.MainController;
import javax.swing.JInternalFrame;

/**
 *
 * @author Amy Leiva
 */
public class MainFrame extends javax.swing.JFrame {
MainController mc;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setupController();
    }

    public void setupController(){
    mc=new MainController(this);
    this.personMenuItem.addActionListener(mc);
    
    this.exitMenuItem.addActionListener(mc);
    this.exitButton.addActionListener(mc);
    this.tableMenuItem.addActionListener(mc);
    }
    public void showChild(JInternalFrame frame,boolean maximizeFrame){
    desktop.add(frame);
    frame.setVisible(true);
    if(maximizeFrame){
    desktop.getDesktopManager().maximizeFrame(frame);
    
    
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        exitButton = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();
        mainMenuBar = new javax.swing.JMenuBar();
        optionsMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        demosMenu = new javax.swing.JMenu();
        personMenuItem = new javax.swing.JMenuItem();
        tableMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton.setActionCommand("exit");
        exitButton.setFocusable(false);
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(exitButton);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        optionsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/app.png"))); // NOI18N

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitMenuItem.setText("Salir");
        exitMenuItem.setActionCommand("exit");
        optionsMenu.add(exitMenuItem);

        mainMenuBar.add(optionsMenu);

        demosMenu.setText("Demos");

        personMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_user_people_person_users_man_5340287 (1).png"))); // NOI18N
        personMenuItem.setText("Persona");
        personMenuItem.setActionCommand("person");
        demosMenu.add(personMenuItem);

        tableMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        tableMenuItem.setText("Table");
        tableMenuItem.setActionCommand("table");
        demosMenu.add(tableMenuItem);

        mainMenuBar.add(demosMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu demosMenu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton exitButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenuItem personMenuItem;
    private javax.swing.JMenuItem tableMenuItem;
    // End of variables declaration//GEN-END:variables
}
