/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wssoftware.pracswing.views;

import com.ssoftware.pracswing.controllers.tablecontroller;
import com.ssoftware.pracswing.models.Person;
import com.ssoftware.pracswing.models.PersonTableModelList;
import com.ssoftware.pracswing.models.PersonsTableModel;


import java.util.Date;
import javax.swing.table.TableModel;

/**
 *
 * @author Amy Leiva
 */
public class PersonListFrame extends javax.swing.JInternalFrame {
private tablecontroller controller;
private PersonsTableModel tableModel;
 private PersonTableModelList tableModelList;
    /**
     * Creates new form table
     */
 
    public PersonListFrame() {
        initComponents();
        setUpcontroller();
        setupPersonTable();
    
   
    }
    
    public void setUpcontroller(){
    controller=new tablecontroller(this);
    this.openButton.addActionListener(controller);
    this.deleteRowButton.addActionListener(controller);
    this.saveButton.addActionListener(controller);
    this.newButton.addActionListener(controller);
    this.closeButton.addActionListener(controller);
    }
     private void setupPersonTable(){
    tableModel = new PersonsTableModel();
    Persontable.setModel(tableModel);
    
    
    
    }
 
  
 
   
   
   
    
    public Person[] getDataTable(){
    Person[] personList;
    int rowCount = this.Persontable.getModel().getRowCount();
    if(rowCount > 0){
    personList=new Person[rowCount];
    for(int i=0;i<rowCount;i++){
    Person p = new Person();
    p.setPersonId(Integer.parseInt(Persontable.getValueAt(i, 0).toString()));
    p.setId(String.valueOf(Persontable.getModel().getValueAt(i, 1)));
    p.setFirstName(String.valueOf(Persontable.getModel().getValueAt(i, 2)));
    p.setSecondName(String.valueOf(Persontable.getModel().getValueAt(i, 3)));
    p.setLastName1(String.valueOf(Persontable.getModel().getValueAt(i, 4)));
    p.setLastName2(String.valueOf(Persontable.getModel().getValueAt(i, 5)));
    p.setBirthDate((Date)(Persontable.getModel().getValueAt(i, 6)));
    p.setAge((short)Persontable.getModel().getValueAt(i, 7));
    p.setGender((char)(Persontable.getModel().getValueAt(i, 8)));
    personList[i] = p;
    }
    
    }else{
    personList=new Person[0];
    }
    return personList;
    
    
    }
    
 
    
     public void setPersonTableModel(TableModel model){
     Persontable.setModel(model);
    }
    
    
     public void setPersonListFile(String path){
    this.fileTitle.setText(path);
    
    }
     public String getPersonListFile(){
        return fileTitle.getText();
    }
   public void addRow() {
tableModel = (PersonsTableModel) Persontable.getModel();
 tableModel.addRow(PersonsTableModel.getDefaultRowData());
      
    }
    
     public void removeRow() {
  tableModel = (PersonsTableModel) Persontable.getModel();
       tableModel.removeRow(Persontable.getSelectedRow());
        
    }
    
   
    
    
    
    
 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        fileTitle = new javax.swing.JLabel();
        openButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        newButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteRowButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        closeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Persontable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listado de personas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coffee_cup.png"))); // NOI18N

        jToolBar2.setRollover(true);

        fileTitle.setText("Archivo");
        jToolBar2.add(fileTitle);

        openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
        openButton.setActionCommand("open");
        openButton.setFocusable(false);
        openButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(openButton);
        jToolBar2.add(jSeparator1);

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        newButton.setActionCommand("newRow");
        newButton.setFocusable(false);
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(newButton);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveButton.setActionCommand("saveTableContent");
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(saveButton);

        deleteRowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_row.png"))); // NOI18N
        deleteRowButton.setActionCommand("deleteRow");
        deleteRowButton.setFocusable(false);
        deleteRowButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteRowButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(deleteRowButton);
        jToolBar2.add(jSeparator2);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closeButton.setFocusable(false);
        closeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(closeButton);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setViewportView(Persontable);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Persontable;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteRowButton;
    private javax.swing.JLabel fileTitle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
